export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERTS = "REMOVE_ALERTS";
export const GET_MESSAGES = "GET_MESSAGES";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const SET_USERS = "SET_USERS";
export const SET_RECENET_SENDER = "SET_RECENT_SENDER";
